GOOGLE_API_KEY = "your-google-api-key-here"
GOOGLE_CSE_ID = "your-custom-search-engine-id-here"
OPENAI_API_KEY = "your-api-key-here"
TWITTER_API_KEY = "your-api-key-here"
TWITTER_API_SECRET = "your-api-secret-here"
TWITTER_ACCESS_TOKEN = "your-access-token-here"
TWITTER_ACCESS_TOKEN_SECRET = "your-access-token-secret-here"
